import "server-only";
import { env, isDemoMode, sponsors } from "@/lib/env";
import { openaiClient } from "@/lib/ai/openai";
import type { SubAgent } from "@/lib/agents/types";
import type { FeatureSummary, Persona } from "@/lib/wine/types";

/**
 * Feature agent — receives the extraction agent's evaluation and produces
 * the three user-facing artifacts:
 *   1. executiveSummary  — 2 sentences shown above the risk card
 *   2. reportMarkdown    — one-page markdown report (download/print)
 *   3. emailDigest       — short markdown preview for the subscribe flow
 *
 * Driven by OpenAI chat.completions with response_format=json_schema. Falls
 * back to a deterministic template when OpenAI is unavailable so the rest
 * of the dashboard stays demoable.
 */

export interface FeatureInput {
  regionId: string;
  persona: Persona;
  /** Risk score from extraction (0–100, higher = worse outlook). */
  score: number;
  /** Vintage quality band from extraction (Great → Poor). */
  qualityBand?: "Great" | "Excellent" | "Good" | "Average" | "Poor";
  /** 1-sentence summary of the dominant risk drivers from extraction. */
  driversSummary?: string;
  /** 1-sentence summary of persona-specific recommendations from extraction. */
  recommendationsSummary?: string;
  /** Optional rationale string from extraction. */
  rationale?: string;
}

export type FeatureOutput = FeatureSummary;

const SYSTEM_PROMPT = `You are the feature agent in a wine-intelligence pipeline.

You receive an evaluation from the upstream extraction agent (risk score, quality band, driver summary, recommendations summary, rationale) plus the target region and persona. You produce THREE user-facing artifacts:

1. executiveSummary — exactly 2 concise sentences. Mention the region by id, the risk level qualitatively, and the dominant driver. No marketing fluff.

2. reportMarkdown — a one-page markdown report (~250-400 words). Sections:
   # Vintage outlook — {regionId}
   ## Risk profile
   ## Key drivers
   ## Recommendations ({persona})
   ## Caveats
   Persona-appropriate tone: operational/agronomic for vineyard, commercial/buying-decision for trade.

3. emailDigest — short markdown digest for a weekly email. About 5-8 lines. Start with a one-line subject, then 2-3 sentences of summary, then a 2-item bullet list of top recommendations.

Output language: English. Be specific. No padding.`;

const RESPONSE_JSON_SCHEMA = {
  name: "feature_output",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: ["executiveSummary", "reportMarkdown", "emailDigest"],
    properties: {
      executiveSummary: { type: "string" },
      reportMarkdown: { type: "string" },
      emailDigest: { type: "string" },
    },
  },
} as const;

function fallback(input: FeatureInput): FeatureOutput {
  const band = input.qualityBand ?? "Average";
  const risk = input.score >= 75 ? "critical" : input.score >= 50 ? "elevated" : input.score >= 25 ? "moderate" : "low";
  const persona = input.persona;
  return {
    executiveSummary: `${input.regionId} is in a ${risk}-risk window with an underlying ${band.toLowerCase()} vintage outlook. ${input.driversSummary ?? "Driver context unavailable."}`,
    reportMarkdown: [
      `# Vintage outlook — ${input.regionId}`,
      ``,
      `## Risk profile`,
      `- **Risk score:** ${input.score}/100 (${risk})`,
      `- **Quality band:** ${band}`,
      ``,
      `## Key drivers`,
      input.driversSummary ?? "_Heuristic fallback: no driver detail available._",
      ``,
      `## Recommendations (${persona})`,
      input.recommendationsSummary ?? "_Recommendations unavailable in fallback mode._",
      ``,
      `## Caveats`,
      `Generated by deterministic fallback because OpenAI was unavailable. Re-run when an OpenAI key is configured for the full report.`,
      input.rationale ? `\n_Extraction rationale: ${input.rationale}_` : "",
    ].join("\n"),
    emailDigest: [
      `**Weekly outlook — ${input.regionId}**`,
      ``,
      `Risk score **${input.score}/100** (${risk}), quality band ${band}.`,
      input.driversSummary ?? "Drivers unavailable.",
      ``,
      input.recommendationsSummary
        ? `Top recommendation: ${input.recommendationsSummary}`
        : "_Recommendations unavailable in fallback mode._",
    ].join("\n"),
  };
}

export const featureAgent: SubAgent<FeatureInput, FeatureOutput> = {
  name: "feature_agent",
  description:
    "Produce the dashboard's executive summary, a downloadable markdown report, and a short email digest from the extraction agent's evaluation. CALL ONLY AFTER extraction_agent has returned, passing its score, quality band, and 1-sentence summaries of drivers + recommendations + rationale.",
  input_schema: {
    type: "object",
    properties: {
      regionId: { type: "string" },
      persona: { type: "string", enum: ["vineyard", "trade"] },
      score: { type: "number", description: "Risk score 0–100 from extraction." },
      qualityBand: {
        type: "string",
        enum: ["Great", "Excellent", "Good", "Average", "Poor"],
        description: "Vintage quality band from extraction.",
      },
      driversSummary: {
        type: "string",
        description: "1-sentence summary of extraction's dominant drivers.",
      },
      recommendationsSummary: {
        type: "string",
        description: "1-sentence summary of extraction's persona-specific recommendations.",
      },
      rationale: { type: "string", description: "Extraction's rationale (full string)." },
    },
    required: ["regionId", "persona", "score"],
  },

  async run(input, ctx) {
    const t0 = Date.now();

    if (isDemoMode || !sponsors.openai) {
      const data = fallback(input);
      return {
        agent: "feature_agent",
        ok: true,
        durationMs: Date.now() - t0,
        data,
        summary: isDemoMode ? "demo · template" : "no openai · template",
      };
    }

    try {
      const client = openaiClient();
      const userMessage = [
        `Region id: ${input.regionId}`,
        `Persona: ${input.persona}`,
        `Risk score: ${input.score}/100`,
        input.qualityBand && `Quality band: ${input.qualityBand}`,
        input.driversSummary && `Drivers: ${input.driversSummary}`,
        input.recommendationsSummary && `Recommendations: ${input.recommendationsSummary}`,
        input.rationale && `Rationale: ${input.rationale}`,
      ]
        .filter(Boolean)
        .join("\n");

      const res = await client.chat.completions.create(
        {
          model: env.OPENAI_MODEL,
          messages: [
            { role: "system", content: SYSTEM_PROMPT },
            { role: "user", content: userMessage },
          ],
          response_format: {
            type: "json_schema",
            json_schema: RESPONSE_JSON_SCHEMA,
          },
          temperature: 0.4,
        },
        { signal: ctx.signal },
      );

      const content = res.choices[0]?.message?.content;
      if (!content) {
        const data = fallback(input);
        return {
          agent: "feature_agent",
          ok: true,
          durationMs: Date.now() - t0,
          data,
          summary: "empty openai · template",
        };
      }

      const data = JSON.parse(content) as FeatureOutput;
      return {
        agent: "feature_agent",
        ok: true,
        durationMs: Date.now() - t0,
        data,
        summary: "summary · report · digest",
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn("[feature] OpenAI call failed, falling back:", message);
      const data = fallback(input);
      return {
        agent: "feature_agent",
        ok: false,
        durationMs: Date.now() - t0,
        data,
        error: message,
        summary: "openai error · template",
      };
    }
  },
};
